### ISSUE TITLE
Quelles licences met-on au projet ?

### ISSUE THREAD

**Issue by Beladric** [Neighbook/.github#6]
Bonjour @UTBM-FISA-TutoredProject/tutored-project,

J'ouvre une issue pour que l'on se mette d'accord sur une licence à utiliser pour protéger le code des _repositories_. De préférence il faudrait une licence permettant de laisser le code open source, tout en nous permettant de monétiser le code et empêchant toute réutilisation à des fins concurrentielles ou lucratives.

***Site édité par Github explicitant les différents type de licences :*** https://choosealicense.com/
***Listes des licences valables selon le droit français :*** https://www.data.gouv.fr/fr/pages/legal/licences/

J'avais déjà envoyé un message à l'ANSSI pour nous orienté dans notre choix, j'attends leur réponse.

**Comment by Beladric** [comment]
J'ai eu la réponse de l'ANSSI. Ils m'ont dit qu'ils ne pouvaient pas me répondre, car leur service juridique ne travail qu'à leurs dépens. De fait, ils m'ont réorienté vers le service juridique de l'UTBM. J'ai donc contacté le service juridique de l'UTBM qui est sur la question.

**Comment by Valentin271** [comment]
A vérifier pour un groupe, mais en tant que personne si on ne met pas de licence par défaut notre travail est "privée".

Sinon un simple copyright peut être suffisant ? A voir quels sont les termes pour que cela soit valable légalement.

**Comment by Beladric** [comment]
@Valentin271 selon la [documentation GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) si on ne met pas de licence à un projet, c'est ***all rights reserved***. De préférence, ce qui serait le mieux, c'est quelque chose qui nous permettrait de faire de l'open source tout en empêchant des réutilisations commerciales ou à des fins concurrentielles. Je pense que les ***copyrights*** sont trop restrictifs. À voir avec la réponse du service juridique (en espérant qu'ils ne me répondent pas un truc à côté de la plaque).

**Comment by Valentin271** [comment]
Qu'est ce que tu entends par _open source_ ? En soit à partir du moment où les sources sont disponible c'est **open**.

Après quelques recherches il n'existe pas de licence open source qui restreint l'utilisation commercial. [Ce lien](https://opensource.stackexchange.com/questions/9805/can-i-license-my-project-with-an-open-source-license-but-disallow-commercial-use#9806) est intéressant et bien expliqué.

Pour résumer, soit on cherche une license non open-source (le repo peut rester public). Soit une license du style GNU GPL où la redistribution doit se faire sous la même licence.

**Comment by Beladric** [comment]
Oui pour le coup, nous ça n'est pas vraiment de l'open source, tout ce que je cherche, c'est laisser le ***repositories*** publique et le droit de faire ce qu'ils veulent avec le code tant qu'ils ne l'utilisent pas à des fins commerciales ou concurrentielles. Sauf qu'une licence comme celle-ci n'existe pas. 

Je cherche surtout à éviter qu'une entreprise au pif débarque et vole le projet.

**Comment by Valentin271** [comment]
@Beladric Tu peux close ça parceque ça me casse les couilles de l'avoir dans mes issues mentionned, thx
